module

public import Mathlib.GroupTheory.Nilpotent

/-!
I am aware that your formalisation of the Feit-Thompson Theorem started with defining and proving
facts about the Fitting subgroup.

In a repository that Inna and I have, we had also started with some preliminaries that included
the Fitting subgroup.

Here is part of what we have: it might be interesting to compare the human and the AI versions
of the same final results.
-/

/-! # The Fitting subgroup of a group

The Fitting subgroup of a group `G` is the subgroup of `G` generated by all the nilpotent,
normal subgroups of `G`.

Here we prove some basic facts:
* `Group.Fitting.eq_top_of_nilpotent`:
  the Fitting subgroup of a nilpotent group is the group itself;
* `Group.Fitting.eq_bot_of_IsSimple_of_not_IsCyclic`:
  the Fitting subgroup of a simple, non-cyclic group is trivial.
* `Subgroup.Fitting.characteristic`:
  the Fitting subgroup is characteristic.
* `Subgroup.Fitting.nontrivial_of_isSolvable`:
  the Fitting subgroup of a nontrivial solvable group is non-trivial.
* `Subgroup.Fitting.centralizer_eq_center_of_isSolvable`:
  the centraliser of the Fitting subgroup of a solvable group is the centre of the Fitting subgroup.
-/

@[expose] public section

variable {G} [Group G]
namespace Subgroup

@[simp]
lemma map_top {H : Subgroup G} : map H.subtype ⊤ = H := by
  ext
  simp

variable (G) in
/--
In a nontrivial solvable group, the last non-trivial element of the derived series
is commutative and nontrivial.
-/
lemma exists_isMulCommutative_nontrivial [Nontrivial G] [IsSolvable G] :
    ∃ n, IsMulCommutative (derivedSeries G n) ∧ Nontrivial (derivedSeries G n) := by
  classical
  have : ∃ n, derivedSeries G n = ⊥ := (isSolvable_def G).mp ‹_›
  let n : ℕ := Nat.find this
  obtain h0 | hn := eq_or_ne n 0
  · simp_all only [Nat.find_eq_zero, derivedSeries_zero, top_ne_bot, n]
  have fn := Nat.find_min (m := n - 1) this (Nat.sub_one_lt hn)
  use n -1
  refine ⟨?_, (nontrivial_iff_ne_bot _).mpr fn⟩
  have : derivedSeries G n = ⊥ := by grind
  refine { is_comm := { comm := ?_ } }
  intro ⟨a, ha⟩ ⟨b, hb⟩
  have hcomm : a * b * a⁻¹ * b⁻¹ ∈ derivedSeries G n := by
    rw [← commutatorElement_def]
    rw [show n = (n - 1) + 1 by grind, derivedSeries_succ]
    exact commutator_mem_commutator ha hb
  rw [this] at hcomm
  simpa only [MulMemClass.mk_mul_mk, Subtype.mk.injEq, ← commutatorElement_eq_one_iff_mul_comm]

/-!
# Formalisation idea

The statement involves an existential. Often, this is a symptom of missing API.

Indeed, from the *proof*, we extract that the stated `n` is *exactly* the predecessor of the
smallest natural number `n` such that `derivedSeries G n = ⊥`.

In the informal context, this number is sometimes called the `derived length` of the group `G`.

It is possible that, for future usage, introducing the concept of `derived length` and using it
extensively could be beneficial.

Note that this would be a definition parallel to the `nilpotencyClass`, which *does* appear
in `mathlib`.
-/
#check Group.nilpotencyClass
/-!
If AIs could automatically sync these notions that would be awesome!
-/

/-- The notation `Z(G)` stands for the center of the group `G`. -/
scoped notation "Z(" G ")" => center G

open Group

/-- Normality is preserved under monoid isomorphisms. -/
@[simp]
lemma normal_map {G'} [Group G'] (H : Subgroup G) (φ : G ≃* G') :
    (map (φ : G →* G') H).Normal ↔ H.Normal := by
  rw [map_equiv_eq_comap_symm]
  refine ⟨fun h ↦ ?_, fun a ↦ normal_comap _⟩
  rw [← sup_bot_eq H, ← (φ : G →* G').ker_eq_bot_iff.mpr φ.injective, ← comap_map_eq,
    map_equiv_eq_comap_symm]
  exact normal_comap (φ : G →* G')

/--
If `p : Subgroup G → Prop` is a property of subgroups of a group `G` that holds on a subgroup `H`
if and only if it holds on the image of `H` under any automorphism of `G`, then the subgroup
generated by all the subgroups satisfying `p` is `Characteristic`.
-/
lemma Characteristic.iSup_ite_of_iff_map (p : Subgroup G → Prop) [DecidablePred p]
    (hp : ∀ φ : G ≃* G, ∀ H, p H ↔ p (map φ H)) :
    Characteristic (⨆ H, if p H then H else ⊥) where
  fixed ψ := by
    rw [comap_equiv_eq_map_symm', MulEquiv.toMonoidHom_eq_coe, map_iSup, iSup_ite]
    -- API idea: extract `let iso` into a definion: a group isomorphism induces an isomorphism
    -- between the `Subgroup` lattices.
    -- Even better, a group homomorphism `φ : G →* G'` induces a monotone map
    -- `Subgroup G' →o Subgroup G` sending `H : Subgroup G'` to `comap φ H`.
    let iso : Subgroup G ≃ Subgroup G :=
      ⟨ map ψ.symm, map ψ,
        fun H ↦ by simp [← map_symm_eq_iff_map_eq],
        fun H ↦ by simp [← map_symm_eq_iff_map_eq] ⟩
    simp only [iSup_bot, bot_le, sup_of_le_left]
    apply Equiv.iSup_congr iso
    simp only [Equiv.coe_fn_mk, iso]
    intro H
    rw [← hp]
    split_ifs with h
    · rw [ciSup_subsingleton h]
    · simp [*]

/--
If `P : Set (Subgroup G)` is a subset of subgroups of `G` that is closed under taking images
under automorphisms, then the subgroup generated by all the subgroups in `P` is `Characteristic`.
-/
lemma Characteristic.sSup_ite_of_iff_map (P : Set (Subgroup G))
  (hp : ∀ φ : G ≃* G, ∀ H, H ∈ P ↔ (map φ H) ∈ P) :
    Characteristic (sSup P) := by
  classical
  suffices sSup P = ⨆ H, if H ∈ P then H else ⊥ by
    rw [this]
    exact Characteristic.iSup_ite_of_iff_map _ hp
  simp [iSup_ite, sSup_eq_iSup]

lemma lowerCentralSeries_two_eq_top_top_top :
    lowerCentralSeries G 2 = ⁅⁅(⊤ : Subgroup G), (⊤ : Subgroup G)⁆, (⊤ : Subgroup G)⁆ := rfl

/--
If the commutator of a subgroup `H` of a group `G` is contained in the centralizer of `H`,
then `lowerCentralSeries H 2` is trivial.

In particular, `H` is (at most) 2-step nilpotent.
See `isNilpotent_of_commutator_le_centralizer` for the proof of nilpotency.
-/
lemma lowerCentralSeries_eq_two_of_commutator_le_centralizer {H : Subgroup G}
    (h : ⁅H, H⁆ ≤ centralizer H) :
    lowerCentralSeries H 2 = ⊥ := by
  rw [lowerCentralSeries_two_eq_top_top_top, commutator_eq_bot_iff_le_centralizer]
  refine map_subtype_le_map_subtype.mp ?_
  rw [← _root_.commutator_def, map_subtype_commutator]
  rw [SetLike.le_def] at h ⊢
  simp only [coe_top, mem_map, subtype_apply, Subtype.exists, exists_and_right,
    exists_eq_right] at h ⊢
  intro x hx
  use Set.mem_of_mem_of_subset hx (commutator_le_self H)
  rw [mem_centralizer_iff]
  aesop

lemma isNilpotent_of_commutator_le_centralizer {H : Subgroup G}
    (h : ⁅H, H⁆ ≤ centralizer H) :
    IsNilpotent H :=
  nilpotent_iff_lowerCentralSeries.mpr ⟨2, lowerCentralSeries_eq_two_of_commutator_le_centralizer h⟩

lemma _root_.Subgroup.isMulCommutative_iff_commutator_eq_bot {H : Subgroup G} :
    IsMulCommutative H ↔ ⁅H, H⁆ = ⊥ := by
  rw [commutator_eq_bot_iff_le_centralizer]
  simp_rw [SetLike.le_def, mem_centralizer_iff]
  refine ⟨fun h x hx ↦ ?_, le_centralizer_iff_isMulCommutative.mp⟩
  exact fun g gH ↦ mul_comm_of_mem_isMulCommutative H gH hx

lemma not_isMulCommutative_derivedSeries_iff_notrivial_derivedSeries_succ (n : ℕ) :
    Nontrivial (derivedSeries G (n + 1)) ↔ ¬ IsMulCommutative (derivedSeries G n) := by
  rw [derivedSeries_succ, isMulCommutative_iff_commutator_eq_bot, nontrivial_iff_ne_bot]

variable (G) in
/--
The Fitting subgroup of a group `G` is the subgroup of `G` generated by all the nilpotent,
normal subgroups of `G`.

We use the notation `F(G)` to denote the Fitting subgroup of `G`.
-/
def Fitting : Subgroup G := sSup {H : Subgroup G | IsNilpotent H ∧ H.Normal}

namespace Fitting

@[inherit_doc]
scoped notation "F(" G ")" => Fitting G

/-- The Fitting subgroup is characteristic. -/
instance characteristic : Characteristic F(G) :=
  Characteristic.sSup_ite_of_iff_map _ fun φ H ↦ by simp [isNilpotent_congr (φ.subgroupMap H)]

/-- The Fitting subgroup of a nilpotent group `G` is the group `G` itself. -/
@[simp]
lemma eq_top_of_nilpotent [IsNilpotent G] : F(G) = ⊤ :=
  eq_top_iff.mpr (le_sSup (by simp [*]))

/-- The `Fitting` subgroup of a simple non-nilpotent group is trivial. -/
theorem eq_bot_of_IsSimpleGroup_of_not_IsNilpotent [IsSimpleGroup G] (hC : ¬ IsNilpotent G) :
    F(G) = ⊥ := by
  unfold Fitting
  simp only [sSup_eq_bot, Set.mem_setOf_eq, and_imp]
  grind only [IsSimpleGroup.eq_bot_or_eq_top_of_normal, isNilpotent_top]

/-- The `Fitting` subgroup of a simple non-cyclic group is trivial. -/
theorem eq_bot_of_IsSimple_of_not_IsCyclic [IsSimpleGroup G] (hC : ¬ IsCyclic G) :
    F(G) = ⊥ := by
  apply eq_bot_of_IsSimpleGroup_of_not_IsNilpotent
  solve_by_elim -- a "manual" proof is `exact fun h ↦ hC inferInstance`

/-!
In a solvable group, the centraliser of the Fitting subgroup is equal to the centre of the
Fitting subgroup.

Ref: https://groupprops.subwiki.org/wiki/Solvable_implies_Fitting_subgroup_is_self-centralising
-/

lemma centralizer_inf_self_eq_center (H : Subgroup G) :
    centralizer H ⊓ H = Z(H).map H.subtype := by
  refine le_antisymm ?_ ?_ <;>
  · intros g hg
    -- `simp_all [mem_centralizer_iff, mem_center_iff]` suffices.
    simp_all only [mem_map, mem_center_iff, Subtype.forall, subtype_apply, Subtype.exists,
      MulMemClass.mk_mul_mk, Subtype.mk.injEq, exists_and_left, exists_prop, exists_eq_right_right,
      mem_inf, mem_centralizer_iff, SetLike.mem_coe, implies_true, and_self]

lemma isMulComm_of_comm_eq_bot {H : Subgroup G} (hH : ⁅H, H⁆ = ⊥) : IsNilpotent H := by
  rw [nilpotent_iff_lowerCentralSeries]
  use 1
  rw [lowerCentralSeries_one, commutator_eq_bot_iff_center_eq_top]
  rw [commutator_eq_bot_iff_le_centralizer, le_centralizer_iff_isMulCommutative] at hH
  exact CommGroup.center_eq_top

lemma nilpotent_of_comm_eq_bot {H : Subgroup G} (hH : ⁅H, H⁆ = ⊥) : IsNilpotent H := by
  rw [nilpotent_iff_lowerCentralSeries]
  use 1
  rw [lowerCentralSeries_one, commutator_eq_bot_iff_center_eq_top]
  rw [commutator_eq_bot_iff_le_centralizer, le_centralizer_iff_isMulCommutative] at hH
  exact CommGroup.center_eq_top

/-- A nontrivial solvable group contains a nontrivial characteristic subgroup that is nilpotent. -/
lemma characteristic_nilpotent [Nontrivial G] [IsSolvable G] :
    ∃ H : Subgroup G, IsNilpotent H ∧ Characteristic H ∧ Nontrivial H := by
  obtain ⟨n, hComm, h0⟩ := exists_isMulCommutative_nontrivial G
  use derivedSeries G n, CommGroup.isNilpotent, derivedSeries_characteristic G n

/-- The Fitting subgroup of a nontrivial solvable group is non-trivial. -/
lemma nontrivial_of_isSolvable [Nontrivial G] [IsSolvable G] : Nontrivial F(G) := by
  obtain ⟨H, hH, hC, hN⟩ := characteristic_nilpotent (G := G)
  rw [nontrivial_iff_ne_bot]
  simp only [Fitting, ne_eq, sSup_eq_bot, Set.mem_setOf_eq, and_imp, not_forall]
  use H, hH, normal_of_characteristic H, (nontrivial_iff_ne_bot H).mp hN

lemma le_fitting_of_normal_of_isNilpotent {B : Subgroup G} (hN : B.Normal) (hNil : IsNilpotent B) :
    B ≤ F(G) :=
  le_sSup (by simp_all)

lemma inf_centralizer_self_le_inf_center :
    F(G) ⊓ centralizer F(G) ≤
      (center F(G)).map F(G).subtype ⊓
        (center (centralizer F(G) : Subgroup G)).map (centralizer F(G)).subtype := by
  intro s ⟨hsF, hsC⟩
  simp only [mem_inf, mem_map, mem_center_iff, Subtype.forall, subtype_apply, Subtype.exists,
    MulMemClass.mk_mul_mk, Subtype.mk.injEq, exists_and_left, exists_prop, exists_eq_right_right]
  constructor
  · exact ⟨fun g h ↦ SemiconjBy.eq (hsC g h), hsF⟩
  · exact ⟨fun g h ↦ (SemiconjBy.eq (h s hsF)).symm, hsC⟩

/-- Please, avoid using this lemma:
`centralizer F(G)` appears on both sides of the inequality!
Prefer `inf_centralizer_self_le_inf_center` instead.
-/
lemma inf_centralizer_self_le_inf_centralizer :
    F(G) ⊓ centralizer F(G) ≤
      centralizer F(G) ⊓ centralizer (centralizer F(G) : Subgroup G) :=
  le_inf (fun z ↦ by aesop) (fun s ⟨hsF, hsC⟩ t ht ↦ (SemiconjBy.eq (ht s hsF)).symm)

-- Refactoring opportunity: this lemma can certainly be reorganised using smaller steps and better
-- structure.
lemma centralizer_le_fitting [IsSolvable G] :
    centralizer F(G) ≤ F(G) := by
  -- The intersection of `F(G)` and its centraliser is normal in the centraliser.
  set C : Subgroup G := centralizer F(G) with hC
  set H : Subgroup G := centralizer F(G) ⊓ F(G) with hH
  have H_le_C : H ≤ C := inf_le_of_left_le le_rfl
  by_contra hcontra
  suffices IsMulCommutative C by
    apply hcontra
    exact le_fitting_of_normal_of_isNilpotent normal_centralizer CommGroup.isNilpotent
  have hC1 : Nontrivial (C ⧸ H.subgroupOf C) := by simp_all
  have hC0 : Nontrivial C := by
    obtain ⟨x, y, xy⟩ := hC1
    obtain ⟨x, hx, rfl⟩ := Quot.exists_rep x
    obtain ⟨y, hy, rfl⟩ := Quot.exists_rep y
    exact nontrivial_of_ne x y fun a ↦ xy (congrArg _ a)
  obtain ⟨n, hBn_nilp, hBn0⟩ := exists_isMulCommutative_nontrivial C
  set Bn := (derivedSeries C n).map C.subtype with hBn
  have Bn_le_F_C : Bn ≤ F(G) ⊓ C := by
    refine le_inf ?_ (map_subtype_le _)
    refine le_fitting_of_normal_of_isNilpotent ?_ ?_
    · exact ConjAct.normal_of_characteristic_of_normal
    · exact CommGroup.isNilpotent
  cases n with
  | zero =>
    simp only [derivedSeries_zero] at hBn_nilp
    refine ⟨⟨fun ⟨a, ha⟩ ⟨b, hb⟩ ↦ ?_⟩⟩
    obtain ⟨⟨C_comm⟩⟩ := hBn_nilp
    simp_all only [inf_le_left, ge_iff_le, QuotientGroup.nontrivial_iff, ne_eq, subgroupOf_eq_top,
      le_inf_iff, Std.le_refl, and_false, not_false_eq_true, derivedSeries_zero, mem_top, map_top,
      and_true]
  | succ n =>
    set B := (derivedSeries C n).map C.subtype with hB
    have BB_le_ZC : ⁅B, B⁆ ≤ centralizer C := by
      unfold B
      rw [← map_commutator, ← derivedSeries_succ]
      trans F(G) ⊓ centralizer F(G)
      · exact Bn_le_F_C
      · exact inf_centralizer_self_le_inf_centralizer.trans (inf_le_of_right_le le_rfl)
    have B_le_C : B ≤ C := map_subtype_le _
    have BB_le_ZB : ⁅B, B⁆ ≤ centralizer B := BB_le_ZC.trans (centralizer_le B_le_C)
    have B_nilp : IsNilpotent B := isNilpotent_of_commutator_le_centralizer BB_le_ZB
    have : Normal B := ConjAct.normal_of_characteristic_of_normal
    have BFitting : B ≤ F(G) := le_fitting_of_normal_of_isNilpotent inferInstance B_nilp
    have B_le_F_C : B ≤ F(G) ⊓ centralizer F(G) := le_inf BFitting B_le_C
    have B_comm : IsMulCommutative B := by
      refine ⟨⟨fun ⟨a, ha⟩ ⟨b, hb⟩ ↦ ?_⟩⟩
      simp only [MulMemClass.mk_mul_mk, Subtype.mk.injEq]
      exact SemiconjBy.eq (B_le_C hb a (BFitting ha))
    exfalso
    apply (not_isMulCommutative_derivedSeries_iff_notrivial_derivedSeries_succ n).mp hBn0
    unfold B at B_comm
    refine ⟨⟨fun ⟨⟨a, aC⟩, ha⟩ ⟨⟨b, bC⟩, hb⟩ ↦ ?_⟩⟩
    obtain ⟨⟨hhh⟩⟩ := B_comm
    simp only [MulMemClass.mk_mul_mk, Subtype.mk.injEq]
    simp only [Subtype.forall, mem_map, subtype_apply, Subtype.exists, exists_and_right,
      exists_eq_right, forall_exists_index, MulMemClass.mk_mul_mk, Subtype.mk.injEq] at hhh
    refine hhh _ ?_ ha _ ?_ hb
    · exact mem_centralizer_iff.mpr aC
    · exact mem_centralizer_iff.mpr bC

-- A general lemma
/--
If the centraliser of a subgroup `H` is contained in `H` itself, then the centraliser is in fact
the whole centre of `H`.
-/
lemma centralizer_eq_center_of_le {H : Subgroup G} (h : centralizer H ≤ H) :
    centralizer H = Z(H).map H.subtype := by
  refine le_antisymm ?_ ?_
  · rw [SetLike.le_def]
    intros x hx
    simp only [mem_map, subtype_apply, Subtype.exists, exists_and_right, exists_eq_right]
    use Set.mem_of_mem_of_subset hx h
    rw [mem_center_iff]
    aesop
  · intro x hx
    simp [mem_center_iff] at hx
    aesop

theorem centralizer_eq_center_of_isSolvable [IsSolvable G] :
    centralizer F(G).carrier = Z(F(G)).map F(G).subtype :=
  centralizer_eq_center_of_le centralizer_le_fitting

end Subgroup.Fitting
